# Generated by Django 5.1.15 on 2026-09-20 18:54

from django.db import migrations, models


def populate_scope_keys(apps, schema_editor):
    UserRole = apps.get_model("accounts", "UsuarioPerfil")
    for role in UserRole.objects.all().iterator():
        role.scope_key = f"branch:{role.branch_id}" if role.branch_id else "global"
        role.save(update_fields=["scope_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_remove_configuracion_uq_config_scope_clave_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuarioperfil',
            name='uq_usuario_perfil_contexto',
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='scope_key',
            field=models.CharField(default='global', editable=False, max_length=32),
        ),
        migrations.RunPython(populate_scope_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='usuarioperfil',
            constraint=models.UniqueConstraint(fields=('user', 'profile', 'company', 'scope_key'), name='uq_usuario_perfil_contexto'),
        ),
    ]
