# Generated by Django 5.1.15 on 2026-09-20 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=150)),
                ('activa', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_sunat', models.CharField(blank=True, db_index=True, max_length=4)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('codigo_inei', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('departamento', models.CharField(db_index=True, max_length=80)),
                ('provincia', models.CharField(db_index=True, max_length=80)),
                ('distrito', models.CharField(db_index=True, max_length=80)),
            ],
            options={
                'ordering': ['departamento', 'provincia', 'distrito'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='core.empresa')),
            ],
            options={
                'ordering': ['empresa_id', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oficinas', to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.JSONField(default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='core.empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='SerieDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serie', models.CharField(max_length=10)),
                ('valor_siguiente', models.PositiveBigIntegerField(default=1)),
                ('valor_minimo', models.PositiveBigIntegerField(default=1)),
                ('valor_maximo', models.PositiveBigIntegerField(default=99999999)),
                ('incremento', models.PositiveIntegerField(default=1)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_documento', to='core.empresa')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_documento', to='core.oficina')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_documento', to='core.sucursal')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='core.tipodocumento')),
            ],
        ),
        migrations.AddIndex(
            model_name='sucursal',
            index=models.Index(fields=['empresa', 'activa'], name='core_sucurs_empresa_b13449_idx'),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_sucursal_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='oficina',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='uq_oficina_sucursal_codigo'),
        ),
        migrations.AddConstraint(
            model_name='configuracion',
            constraint=models.UniqueConstraint(fields=('empresa', 'sucursal', 'clave'), name='uq_config_scope_clave'),
        ),
        migrations.AddIndex(
            model_name='seriedocumento',
            index=models.Index(fields=['sucursal', 'tipo_documento', 'activa'], name='core_seried_sucursa_a9824e_idx'),
        ),
        migrations.AddConstraint(
            model_name='seriedocumento',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'serie'), name='uq_serie_empresa_tipo_serie'),
        ),
        migrations.AddConstraint(
            model_name='seriedocumento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_siguiente__gte', 1)), name='ck_serie_siguiente_positivo'),
        ),
        migrations.AddConstraint(
            model_name='seriedocumento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_maximo__gte', models.F('valor_minimo'))), name='ck_serie_rango_valido'),
        ),
    ]
