# Generated by Django 5.1.15 on 2026-09-20 18:54

from django.db import migrations, models


def populate_scope_keys(apps, schema_editor):
    Setting = apps.get_model("core", "Configuracion")
    for setting in Setting.objects.all().iterator():
        setting.scope_key = f"branch:{setting.sucursal_id}" if setting.sucursal_id else "global"
        setting.save(update_fields=["scope_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='configuracion',
            name='uq_config_scope_clave',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='scope_key',
            field=models.CharField(default='global', editable=False, max_length=32),
        ),
        migrations.RunPython(populate_scope_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='configuracion',
            constraint=models.UniqueConstraint(fields=('empresa', 'scope_key', 'clave'), name='uq_config_scope_clave'),
        ),
    ]
