# Generated by Django 5.1.15 on 2026-09-20 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('factor_base', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almacenes', to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('purchase', 'Compra'), ('output', 'Salida'), ('transfer', 'Traslado'), ('adjustment', 'Ajuste')], db_index=True, max_length=20)),
                ('referencia', models.CharField(blank=True, db_index=True, max_length=100)),
                ('observacion', models.TextField(blank=True)),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='inventory.almacen')),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='inventory.almacen')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='core.sucursal')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventory.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=180)),
                ('stock_minimo', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('afecta_stock', models.BooleanField(default=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventory.marca')),
                ('unidad_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventory.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=3)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=16)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=16)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex', to='inventory.almacen')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex_entries', to='inventory.movimientoinventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex', to='inventory.producto')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('ultimo_costo', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.producto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cantidad_base', models.DecimalField(decimal_places=4, max_digits=16)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventory.movimientoinventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_movimiento', to='inventory.producto')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_movimiento', to='inventory.unidadmedida')),
            ],
        ),
        migrations.AddConstraint(
            model_name='almacen',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='uq_almacen_sucursal_codigo'),
        ),
        migrations.AddIndex(
            model_name='kardex',
            index=models.Index(fields=['producto', 'almacen', '-created_at'], name='inventory_k_product_cbe460_idx'),
        ),
        migrations.AddIndex(
            model_name='productostock',
            index=models.Index(fields=['almacen', 'producto'], name='inventory_p_almacen_5aec6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='productostock',
            constraint=models.UniqueConstraint(fields=('producto', 'almacen'), name='uq_stock_producto_almacen'),
        ),
        migrations.AddConstraint(
            model_name='productostock',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='ck_stock_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['sucursal', 'created_at'], name='inventory_m_sucursa_6aa97f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo', 'created_at'], name='inventory_m_tipo_bc803a_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'nombre'], name='inventory_p_activo_33ba4e_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_barras'], name='inventory_p_codigo__07ebb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventariodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_movdetalle_cantidad_positiva'),
        ),
    ]
