# Generated by Django 5.1.15 on 2026-09-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_movimientoinventario_idempotency_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='producto',
            name='inventory_p_codigo__07ebb3_idx',
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('purchase', 'Compra'), ('output', 'Salida'), ('transfer', 'Traslado'), ('adjustment', 'Ajuste')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
