# Generated by Django 5.1.15 on 2026-09-20 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('es_efectivo', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Arqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(db_index=True)),
                ('total_arqueo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado'), ('cancelled', 'Anulado')], db_index=True, default='open', max_length=12)),
                ('cerrado_at', models.DateTimeField(blank=True, null=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arqueos', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arqueos_cerrados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arqueos', to='core.sucursal')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arqueos', to='treasury.caja')),
            ],
        ),
        migrations.CreateModel(
            name='CierreDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(db_index=True)),
                ('numero_deposito', models.CharField(blank=True, max_length=80)),
                ('importe_deposito', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('anulado', models.BooleanField(default=False)),
                ('arqueos', models.ManyToManyField(related_name='cierres_diarios', to='treasury.arqueo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_diarios', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_diarios', to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='ConteoEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('arqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos', to='treasury.arqueo')),
            ],
        ),
        migrations.CreateModel(
            name='ArqueoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.PositiveIntegerField()),
                ('categoria', models.CharField(db_index=True, max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('arqueo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='treasury.arqueo')),
                ('forma_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arqueo_detalles', to='treasury.formapago')),
            ],
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='uq_caja_sucursal_codigo'),
        ),
        migrations.AddIndex(
            model_name='arqueo',
            index=models.Index(fields=['sucursal', 'fecha'], name='treasury_ar_sucursa_778424_idx'),
        ),
        migrations.AddIndex(
            model_name='arqueo',
            index=models.Index(fields=['cajero', 'fecha'], name='treasury_ar_cajero__67ff15_idx'),
        ),
        migrations.AddConstraint(
            model_name='arqueo',
            constraint=models.UniqueConstraint(fields=('sucursal', 'caja', 'cajero', 'fecha'), name='uq_arqueo_contexto_fecha'),
        ),
        migrations.AddIndex(
            model_name='cierrediario',
            index=models.Index(fields=['sucursal', 'fecha'], name='treasury_ci_sucursa_070c3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='conteoefectivo',
            constraint=models.UniqueConstraint(fields=('arqueo', 'denominacion'), name='uq_conteo_denominacion'),
        ),
        migrations.AddIndex(
            model_name='arqueodetalle',
            index=models.Index(fields=['arqueo', 'categoria'], name='treasury_ar_arqueo__a2a414_idx'),
        ),
        migrations.AddConstraint(
            model_name='arqueodetalle',
            constraint=models.UniqueConstraint(fields=('arqueo', 'numero_linea'), name='uq_arqueo_numero_linea'),
        ),
    ]
