# Generated by Django 5.1.15 on 2026-09-20 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=4370)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('firmware', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('last_connection', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('maintenance', 'Mantenimiento')], db_index=True, default='active', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_devices', to='core.sucursal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_pin', models.CharField(db_index=True, max_length=32)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('device_status', models.CharField(blank=True, max_length=20)),
                ('verification_method', models.CharField(choices=[('fingerprint', 'Huella'), ('face', 'Rostro'), ('card', 'Tarjeta'), ('password', 'Contraseña'), ('other', 'Otro')], default='other', max_length=20)),
                ('source_event_id', models.CharField(blank=True, max_length=100)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('raw_data', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='attendance.attendancedevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='accounts.empleado')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'occurred_at'], name='attendance__employe_698a0b_idx'), models.Index(fields=['device', 'occurred_at'], name='attendance__device__ac7eaa_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'biometric_pin', 'occurred_at', 'verification_method'), name='uq_attendance_event_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('first_entry', models.DateTimeField(blank=True, null=True)),
                ('last_exit', models.DateTimeField(blank=True, null=True)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='pending', max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendance', to='accounts.empleado')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'status'], name='attendance__date_a41095_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='uq_daily_attendance_employee_date')],
            },
        ),
    ]
